### ISSUE TITLE
Issues with TensorQTL in Trans Mode

### ISSUE THREAD

**Issue by hnaeem** [broadinstitute/tensorqtl#125] opened 2024-02-27 10:48 UTC
Dear,

TensorQTL in trans mode (tran-eQTL) displays the following error message at the Terminal window. It also shows the warning: " 'rfunc' cannot be imported. R and the 'rpy2' Python package are needed", despite both the R and rpy2 packages being available on the HPC.
Any advice will be appreciated
Thank you.

Warning: 'rfunc' cannot be imported. R and the 'rpy2' Python package are needed.
[Feb 26 15:32:26] Running TensorQTL: trans-QTL mapping

    WARNING: using CPU!
    reading phenotypes (/gpfs/projects/SDR_transcriptomics_ymokrab/collaborate/khalid_lab/qgp_mitchondrial_proj/eQTL_analysis/genes/QTL/trans_qtl/2_transQTL/input/MT_gene_expression_inv_transform_fastqtl.bed.gz)
    reading covariates (/gpfs/projects/SDR_transcriptomics_ymokrab/collaborate/khalid_lab/qgp_mitchondrial_proj/eQTL_analysis/genes/QTL/trans_qtl/2_transQTL/input/covariates_MT.txt.gz)
    Mapping files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3.09it/s]
    /gpfs/software/genomics/tensorqtl/venv/lib/python3.6/site-packages/tensorqtl/genotypeio.py:145: PerformanceWarning: Slicing with an out-of-order index is generating 306 times more chunks
    self.bed = self.bed[:,ix]
    p-value threshold: 1e-05
    trans-QTL mapping
    1882 samples
    37 phenotypes
    50 covariates
    /gpfs/software/genomics/tensorqtl/venv/lib/python3.6/site-packages/tensorqtl/core.py:52: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
    The boolean parameter 'some' has been replaced with a string parameter 'mode'.
    Q, R = torch.qr(A, some)
    should be replaced with
    Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at ../aten/src/ATen/native/BatchLinearAlgebra.cpp:1937.)
    self.Q_t, _ = torch.qr(C_t - C_t.mean(0))
    342578 variants
    processing batch 18/18
    elapsed time: 0.11 min
    342578 variants passed MAF >= 0.01 filtering
    done.
    filtering out cis-QTLs (within +/-5Mb)
    writing output
    [Feb 26 15:37:22] Finished mapping
    Traceback (most recent call last):
    File "/gpfs/software/genomics/tensorqtl/venv/bin/tensorqtl", line 8, in
    sys.exit(main())
    TypeError: 'module' object is not callable

**Comment by francois-a** [comment] 2024-08-24 00:49
Duplicate of https://github.com/broadinstitute/tensorqtl/issues/123.

**Closed by francois-a** 2024-08-24 00:49 UTC
