### ISSUE TITLE
MAF vs Beta looks a bit unexpected

### ISSUE THREAD

**Issue by maxozo** [broadinstitute/tensorqtl#98] opened 2023-07-17 18:06 UTC
Hi, I a very simple question, we processed the same dataset with tensorqtl and matrixqtl and plotted betas (slope) vs maf.
For the matrixqtl we got what we expect, a higher betas at lower Mafs and vice versa, but for tensorqtl output this was not as evident (see image attachet). Is there a simple explanation for this? Is it because betas are estimated differently in TensorQTL?
Thank you,
![Artboard 1](https://github.com/broadinstitute/tensorqtl/assets/22347136/3d6eb53a-cea3-43b6-9037-e36d2bc828ea)

**Comment by francois-a** [comment] 2023-07-17 19:10
Hi, the outputs from the two methods should be identical (and are in unit tests). Can you provide a small dataset that reproduces this behavior?

**Comment by francois-a** [comment] 2024-01-05 07:28
Closing since this looks like a user error. Please reopen if needed.

**Closed by francois-a** 2024-01-05 07:28 UTC
